package net.minecraft.src;

import java.util.ArrayList;
import java.util.List;

public class Session {
	public static List registeredBlocksList = new ArrayList();
	public String username;
	public String sessionId;
	public String mpPassParameter;
	public static List creativeInventoryItems;

	public Session(String string1, String string2) {
		this.username = string1;
		this.sessionId = string2;
	}

	static {
		registeredBlocksList.add(Block.stone);
		registeredBlocksList.add(Block.cobblestone);
		registeredBlocksList.add(Block.brick);
		registeredBlocksList.add(Block.dirt);
		registeredBlocksList.add(Block.planks);
		registeredBlocksList.add(Block.wood);
		registeredBlocksList.add(Block.leaves);
		registeredBlocksList.add(Block.torch);
		registeredBlocksList.add(Block.glass);
		registeredBlocksList.add(Block.stairSingle);
		registeredBlocksList.add(Block.cobblestoneMossy);
		registeredBlocksList.add(Block.sapling);
		registeredBlocksList.add(Block.plantYellow);
		registeredBlocksList.add(Block.plantRed);
		registeredBlocksList.add(Block.mushroomBrown);
		registeredBlocksList.add(Block.mushroomRed);
		registeredBlocksList.add(Block.sand);
		registeredBlocksList.add(Block.gravel);
		registeredBlocksList.add(Block.sponge);
		registeredBlocksList.add(Block.clothRed);
		registeredBlocksList.add(Block.clothOrange);
		registeredBlocksList.add(Block.clothYellow);
		registeredBlocksList.add(Block.clothChartreuse);
		registeredBlocksList.add(Block.clothGreen);
		registeredBlocksList.add(Block.clothSpringGreen);
		registeredBlocksList.add(Block.clothCyan);
		registeredBlocksList.add(Block.clothCapri);
		registeredBlocksList.add(Block.clothUltramarine);
		registeredBlocksList.add(Block.clothViolet);
		registeredBlocksList.add(Block.clothPurple);
		registeredBlocksList.add(Block.clothMagenta);
		registeredBlocksList.add(Block.clothRose);
		registeredBlocksList.add(Block.clothDarkGray);
		registeredBlocksList.add(Block.clothGray);
		registeredBlocksList.add(Block.cloth);
		registeredBlocksList.add(Block.oreCoal);
		registeredBlocksList.add(Block.oreIron);
		registeredBlocksList.add(Block.oreGold);
		registeredBlocksList.add(Block.blockSteel);
		registeredBlocksList.add(Block.blockDiamond);
		registeredBlocksList.add(Block.blockGold);
		registeredBlocksList.add(Block.bookshelf);
		registeredBlocksList.add(Block.tnt);
		registeredBlocksList.add(Block.obsidian);
		registeredBlocksList.add(Block.jukebox);
		creativeInventoryItems = new ArrayList();
		creativeInventoryItems.add(Item.appleGold);
		creativeInventoryItems.add(Item.appleRed);
		creativeInventoryItems.add(Item.arrow);
		creativeInventoryItems.add(Item.bow);
		creativeInventoryItems.add(Item.striker);
		creativeInventoryItems.add(Item.swordSteel);
		creativeInventoryItems.add(Item.pickaxeSteel);
		creativeInventoryItems.add(Item.axeSteel);
		creativeInventoryItems.add(Item.shovel);
		creativeInventoryItems.add(Item.hoeSteel);
		creativeInventoryItems.add(Item.swordWood);
		creativeInventoryItems.add(Item.pickaxeWood);
		creativeInventoryItems.add(Item.axeWood);
		creativeInventoryItems.add(Item.shovelWood);
		creativeInventoryItems.add(Item.hoeWood);
		creativeInventoryItems.add(Item.swordStone);
		creativeInventoryItems.add(Item.pickaxeStone);
		creativeInventoryItems.add(Item.axeStone);
		creativeInventoryItems.add(Item.shovelStone);
		creativeInventoryItems.add(Item.hoeStone);
		creativeInventoryItems.add(Item.swordGold);
		creativeInventoryItems.add(Item.pickaxeGold);
		creativeInventoryItems.add(Item.axeGold);
		creativeInventoryItems.add(Item.shovelGold);
		creativeInventoryItems.add(Item.hoeGold);
		creativeInventoryItems.add(Item.swordDiamond);
		creativeInventoryItems.add(Item.pickaxeDiamond);
		creativeInventoryItems.add(Item.axeDiamond);
		creativeInventoryItems.add(Item.shovelDiamond);
		creativeInventoryItems.add(Item.hoeDiamond);
		creativeInventoryItems.add(Item.bucketEmpty);
		creativeInventoryItems.add(Item.bucketWater);
		creativeInventoryItems.add(Item.bucketLava);
		creativeInventoryItems.add(Item.bucketMilk);
		creativeInventoryItems.add(Item.boat);
		creativeInventoryItems.add(Item.minecartEmpty);
		creativeInventoryItems.add(Item.minecartBox);
		creativeInventoryItems.add(Item.minecartEngine);
		creativeInventoryItems.add(Item.bowlEmpty);
		creativeInventoryItems.add(Item.bowlSoup);
		creativeInventoryItems.add(Item.bread);
		creativeInventoryItems.add(Item.egg);
		creativeInventoryItems.add(Item.porkRaw);
		creativeInventoryItems.add(Item.porkCooked);
		creativeInventoryItems.add(Item.feather);
		creativeInventoryItems.add(Item.flint);
		creativeInventoryItems.add(Item.stick);
		creativeInventoryItems.add(Item.leather);
		creativeInventoryItems.add(Item.gunpowder);
		creativeInventoryItems.add(Item.silk);
		creativeInventoryItems.add(Item.book);
		creativeInventoryItems.add(Item.reed);
		creativeInventoryItems.add(Item.redstone);
		creativeInventoryItems.add(Item.seeds);
		creativeInventoryItems.add(Item.wheat);
		creativeInventoryItems.add(Item.ingotGold);
		creativeInventoryItems.add(Item.ingotIron);
		creativeInventoryItems.add(Item.diamond);
		creativeInventoryItems.add(Item.clay);
		creativeInventoryItems.add(Item.brick);
		creativeInventoryItems.add(Item.coal);
		creativeInventoryItems.add(Item.doorWood);
		creativeInventoryItems.add(Item.doorSteel);
		creativeInventoryItems.add(Item.painting);
		creativeInventoryItems.add(Item.paper);
		creativeInventoryItems.add(Item.recordCat);
		creativeInventoryItems.add(Item.record13);
		creativeInventoryItems.add(Item.sign);
		creativeInventoryItems.add(Item.saddle);
		creativeInventoryItems.add(Item.slimeBall);
		creativeInventoryItems.add(Item.snowball);
		creativeInventoryItems.add(Item.fishingRod);
		creativeInventoryItems.add(Item.helmetChain);
		creativeInventoryItems.add(Item.plateChain);
		creativeInventoryItems.add(Item.legsChain);
		creativeInventoryItems.add(Item.bootsChain);
		creativeInventoryItems.add(Item.helmetLeather);
		creativeInventoryItems.add(Item.plateLeather);
		creativeInventoryItems.add(Item.legsLeather);
		creativeInventoryItems.add(Item.bootsLeather);
		creativeInventoryItems.add(Item.helmetSteel);
		creativeInventoryItems.add(Item.plateSteel);
		creativeInventoryItems.add(Item.legsSteel);
		creativeInventoryItems.add(Item.bootsSteel);
		creativeInventoryItems.add(Item.helmetGold);
		creativeInventoryItems.add(Item.plateGold);
		creativeInventoryItems.add(Item.legsGold);
		creativeInventoryItems.add(Item.bootsGold);
		creativeInventoryItems.add(Item.helmetDiamond);
		creativeInventoryItems.add(Item.plateDiamond);
		creativeInventoryItems.add(Item.legsDiamond);
		creativeInventoryItems.add(Item.bootsDiamond);
		ModLoader.RegisterAllBlocks(registeredBlocksList);
		System.out.println(registeredBlocksList.size());
	}
}
